@startuml
class Celular { -imei:String; -marca:String; -modelo:String }
class Bateria { -modelo:String; -capacidad:int }
class Usuario { -nombre:String; -dni:String }

Celular "1" o-- "1" Bateria
Celular "1" <--> "1" Usuario
@enduml